### PR TITLE
Add Moderustic to Google Fonts

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @Tural!

I'm Emma, I work with the Google team and I'm in charge of your project onboarding :)

You will find here the changes I've made in order to fit with the GF specs. I generated the sources in UFO, so you can use it also. 

Let me know if you have any questions. I'll reach you soon by email, about the release of the font and the promotion! 
Thank you!

Emma

### CODE REVIEW

**Comment by Tural** [comment]
Hi @emmamarichal!

Thank you for your help. Feel free to write if you have any questions or if there is anything I can do.

**Comment by emmamarichal** [comment]
If all is good on your side, you can merge that PR! I'll let you know for the next steps!

**Comment by Tural** [comment]
Sorry. I have little experience with GitHub. :)

**Comment by emmamarichal** [comment]
No problem :) I just sent you an email about the font promotion and the things I need!
Thank you again!

**Pull request merged**
